Q rscan
MartinBruun/P3-Projekt pull request #41
Opened 2020-11-11 14:15 UTC by mkju19

2020-11-12 22:19 UTC, saxjax commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/MainActivity.cs
>              base.OnCreate(savedInstanceState);
hvad er det base er?

2020-11-12 22:22 UTC, saxjax approved these changes

2020-11-13 21:57 UTC, MartinBruun requested changes
Resolve conflicts!
Dette gøres bedst via command line, og det er SUPER NEMT at fucke op! Gør det helst sammen med en og FØLG INSTRUKSERNE!
Jeg override en hel fil på coolshop da jeg gjorde det forkert. Ikke den bedste oplevelse :P

2020-11-13 21:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/MainActivity.cs
>              base.OnCreate(savedInstanceState);
base er "super klassen". Aka. når Tablet har en funktion "Tablet.SomeFunc" der kalder "base" så kalder den "Component.SomeFunc".
Component.SomeFunc() {return 5}
Tablet.SomeFunc() { return base.SomeFunc() + 1 } == 6

2020-11-13 21:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/MainActivity.cs
Denne linje er en kopi af linjen 2 over, så linje 34 kan godt slettes. (men ikke linje 32!)

Skal ZXing ikke også få sine Permissions sat ind her? Eller ??

2020-11-13 21:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/View/ScanningPage.xaml.cs
> +            Device.BeginInvokeOnMainThread(() =>
Hvordan kan denne funktionalitet bruges i en ViewModel istedet for i Code Behind?

2020-11-13 21:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/App.xaml.cs
>          }
Hvordan fungere ScanningPage?
Er det en speciel ZXing page man skifter til, og som returnere et output?
Eller er det mere en "test page", hvor ZXing er implementeret, som kan kopieres til andre ViewModels der ønsker at bruge denne funktionalitet?

2020-11-13 21:58 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/View/ScanningPage.xaml.cs
> +            Device.BeginInvokeOnMainThread(() =>
Synes det er vigtigt vi får styr på det, da ZXing funktionaliteten skal bruges af ViewModels :)

2020-11-17 10:06 UTC, closed without merging