Xaml
MartinBruun/P3-Projekt pull request #42
Opened 2020-11-13 15:38 UTC by Rallefar1103

2020-11-13 21:50 UTC, MartinBruun requested changes
Generel kommentar:
Super fedt!
Husk at ændrer LoginViewModelTest til SignInViewModelTest (da alle test pt. fejler og der ikke kan merges ;) )

Tænker det ser godt ud som det står. Men lad os få skelettet sat op nogenlunde, og så ellers begynde at uddele funktioner til hinanden tænker jeg :) (evt. flere hvis de overlapper) så tror jeg vi er godt på vej!

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Model/RobotPacket.cs
>           GPS RoverGps { get; set; }
Bare kald den Rover :)

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Model/RobotPacket.cs
>           GPS RoverGps { get; set; }
Og mangler en GPS Base ;)

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/TurfTankRegistrationApplication.csproj
>    </ItemGroup>
Hvad er Registration_views kontra Validation views? Hvad er et validation view?

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/BaseViewModel.cs
> -using System.Text;
Genopret denne fil og sæt alle viewmodels til at inherit fra den ;)

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/BaseViewModel.cs
> -using System.Text;
Tænker nærmest bare copy paste skulle virke

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/SignInViewModel.cs
> +    {
Denne burde virke når den inheriter fra BaseViewModel.
HUSK at ændrer i unittestene så det er den her den bruger. Så burde testene virke igen.

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/SignInViewModel.cs
> +
Alt efter hvordan vi kommer til at håndtere navigation kan det overvejes.
Her er det en "NavigationService" klasse der holder styr på alle navigationer.
En måde at gøre det på jeg fandt på internettet. Kan se om den kan implementeres hvis folk er interesserede :)

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/SignInViewModel.cs
> +
Tænker det er smart at ViewModel kan håndtere hvordan der sker navigation (som kan ses eksempelvis på linje 64)

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/ViewModel1.cs
> +    public class ViewModel1
ViewModel1 Skal bare slettes når vi har fået det "rigtige" sat op

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/ViewModel1.cs
> +    public class ViewModel1
Men ikke før det andet virker ;) Den er god som opslagsværk

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Views/LoginView.xaml
>      </ContentView.BindingContext>
Tænker denne fil godt kan slettes? Hvis den er lavet om til SignInView

2020-11-13 21:50 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Views/Validation_views/ScanValidationContainer.xaml
> +    </ContentView.Content>
Hvad er det her for en fil?

2020-11-14 07:43 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/TurfTankRegistrationApplication.csproj
>    </ItemGroup>
Registration_views var egentlig tænkt som en mappe der kunne holde de view-komponenter som vi bruger på den side, som eksempelvis knappen med komponent navnet i sig, men eftersom, at jeg ikke lige pt kan tænke mig til andre view-komponenter på den skærm så skrotter jeg den nok igen.

Validation_views er en folder der skal håndtere de view-komponenter der har med valideringsbeskeder at gøre. Her tænker jeg et overlay med en container, hvori der fremgår en eller anden valideringsbesked (success for korrekt scan, error for når der sker en fejl).

2020-11-14 07:44 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/SignInViewModel.cs
> +
enig. Jeg prøver dog nok bare at implementere det direkte i den viewmodel jeg arbejder i, men så kan det være en del af refaktoreringen.

2020-11-14 07:45 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Views/Validation_views/ScanValidationContainer.xaml
> +    </ContentView.Content>
Det er påtænkt, at denne xaml fil skal indeholde den kode/det viewkomponent der udgør en valideringsbesked for brugeren efter scan.

2020-11-14 10:42 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Pages/SignInPage.xaml.cs
> +            InitializeComponent();
Har ikke set den her måde at gøre det på før?
Og hvor får den Navigation fra? Hvad er det for en magisk ting :P

2020-11-14 10:44 UTC, MartinBruun requested changes

2020-11-14 10:44 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/BaseViewModel.cs
> -        #region INotifyPropertyChanged
BaseViewModel er stadig slettet ;)

2020-11-14 10:44 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/SignInViewModel2.cs
> +    {
Hvorfor SignInViewModel2??? Kan 2 tallet ikke slettes?

og husk at omdefiner testene i LoginViewModelTest til SignInViewModelTest ;)
Ellers får du aldrig mulighed for at merge :P

2020-11-14 11:06 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Pages/SignInPage.xaml.cs
> +            InitializeComponent();
Det er mega fedt! Synes vi skal gøre det sådan her fremadrettet. Det holder vores XAML lidt mere clean. 
Navigation er noget den nedarver fra Page :-)

2020-11-14 11:07 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/SignInViewModel2.cs
> +    {
Fordi du havde lavet en masse ting i SignInViewModel som jeg ikke ville slette og jeg orkede ikke til at udkommentere det hele, så jeg lavede bare lige en midlertidig SignInViewModel2 til at sætte navigering op for siden :-)

2020-11-16 11:13 UTC, merged