Wifi
MartinBruun/P3-Projekt pull request #55
Opened 2020-11-20 22:05 UTC by Rallefar1103

2020-11-25 10:13 UTC, MartinBruun requested changes
Generelt vil jeg sige det er super fed!

Dog er jeg lidt ærgelig over så meget implementation, og ingen test. Kan ikke rigtig stole på om det virker, og har ikke pt. tiden til at tænde op for den og kører en fuldstændig integrationstest ;)

2020-11-25 10:13 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
> +
Kunne overveje at lave dem som properties og sætte det i constructoren :)

2020-11-25 10:13 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Model/Controller.cs
> +                return ID;
Hmm. SetupWifi er vel ikke en del af GetSerialNumber?
SetupWifi er det sidste der skal håndteres (før save funktionen må virke), og GetSerialNumber skal vel bruge den WifiConnecter du har sat op, og ikke returnere en hardcoded string?

2020-11-25 10:13 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Model/Controller.cs
> +                return ID;
Er det fordi planen er at skulle merge det her først, og så bagefter implementere GetSerialNumber?

2020-11-25 10:13 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RobotRegistrationViewModel.cs
> +            Callback = new Action<object, string>(OnDataReceived);
Hvorfor hedder den "DidChange" når den navigere til en side? Burde den ikke hedde "ChangeControllerSN" istedet for "DidChangeControllerSN"?

2020-11-25 13:02 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
> +
Planen er, at der bliver lavet en scanwifi funktion der søger efter omkringliggende netværk. Når den så finder eksempelvis SSID og PASSW for robotten, så sendes det SSID og PASSW med videre til metoden/constructoren af klassen også forbindes der derefter.

2020-11-25 13:02 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RobotRegistrationViewModel.cs
> +            Callback = new Action<object, string>(OnDataReceived);
Jo :D

2020-11-26 14:13 UTC, MartinBruun approved these changes

2020-11-26 14:16 UTC, merged