Completed the actual GetRoverSerialNumber method for correct use as w…
MartinBruun/P3-Projekt pull request #62
Opened 2020-12-02 12:36 UTC by Rallefar1103

…ell as a test version

2020-12-02 14:32 UTC, MartinBruun requested changes
Lige nogle små rettelser. Generelt set det rigtig fedt ud :)

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/App.cs
>  		}
Der er en parantes for meget der giver Syntax Error ;)

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
>              var formattedSSID = $"\"{ssid}\"";
Er ideen at password er en statisk værdi?

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
>          {
Sæt gerne kommentarer, eg. /// med summary af hvad den gør og definition af parametrene.

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +    {
Lav gerne et /// summary, da jeg ingen ide har til hvad "NorthCommands" betyder?
Er det kommandoer man kun må sende når mobilen peger mod nord :P

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +        {
Denne constructor har 100% behov for en forklaring :P

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +    {
Hvad er SOSVER? Skriv gerne i koden som /// summary istedet for her på github :)

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +            string URL = $"http://{RobotIP}:8888/rover";
Istedet for at lave HttpClient fra bunden, så barer brug GPS.API.GetById("");
Er der da noget specielt der ikke dækkes af den funktion, som skal tilføjes til vores API? Synes det er mærkeligt at ViewModel direkte selv kontakter vores Connection lag udenom vores modeller?

2020-12-02 14:32 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/WifiPageViewModel.cs
> +        public async void ConnectToRobot()
Tænker jeg nok jeg er enig i :)

2020-12-02 17:07 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/App.cs
>  		}
haha ja det så jeg :D

2020-12-02 17:08 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
>              var formattedSSID = $"\"{ssid}\"";
ja for det bliver højst sandsynligt det samme

2020-12-02 17:08 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +    {
hahahaha ja!!! you guessed it

2020-12-02 17:08 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +        {
self explanatory!

2020-12-02 17:09 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +            string URL = $"http://{RobotIP}:8888/rover";
true, men jeg skulle egentlig bare have det til at virke. Jeg har jo ikke refaktoreret endnu ;)!

2020-12-02 19:35 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +            string URL = $"http://{RobotIP}:8888/rover";
true ;)

2020-12-02 19:36 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
>              var formattedSSID = $"\"{ssid}\"";
Det er rigtigt, vi kan jo vælge det nu jeg tænker over det :P

2020-12-02 19:57 UTC, MartinBruun requested changes
Jeg bliver lige nødt til at starte med, at jeg synes det ser super mega fedt ud xD

Kommer nemt til at sætte kommentarer kun på det der er problematisk, men siden jeg kun sætter 4 kommentarer, så betyder det altså at alle de andre linjer kode er totalt spitze klasse ;)

2020-12-02 19:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
>          public void ConnectToWifi(string ssid)
Small nitpick, men put det gerne ind i en < summary > < /summary > tag.

Hvis du skriver /// ovenover ConnectToWifi, så vil der automatisk komme en template op som du kan udfylde :)
Det gør at når vi "peger" på ConnectToWifi andre steder i programmet, så får vi din beskrivelse (og kan dermed se den i hele programmet!)

Super fed dokumentation ellers!

2020-12-02 19:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +    {
Er dog stadig forvirret over hvorfor den hedder "North" xD
Men god forklaring ellers! (gør gerne det med /// som beskrevet før. Igen, super nitpicky :P )

2020-12-02 19:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TestUnit/ViewModel/RoverRegVMTest.cs
> +            string actual = testObject.RoverResponse;
Hvorfor giver strengen "cmd" -> "Leanne Graham"???

Kan ikke lige følge hvordan en parsing af "cmd" giver det navn :P

Hvis det er fordi den forbinder til databasen og henter noget derfra (eller en anden forbindelse via en model), så kan den evt. mockes ud ved en 

mockRegistrationDBAPI= Substitute.For<IGPS>();
GPS Rover = new GPS(GPSType.ROVER);
mockRegistrationDBAPI.GetById("cmd").Returns(Rover);
GPS.API = mockRegistrationDBAPI

2020-12-02 19:57 UTC, MartinBruun commented on TurfTankRegistrationApplication/TestUnit/ViewModel/RoverRegVMTest.cs
> +            string actual = testObject.RoverResponse;
PS: husk at merge med master. Det hedder GPSType.ROVER nu, og ikke GPSType.Rover ud fra det Marco han har lavet med QRkoderne (eller også er det QRType.ROVER istedet for QRType.Rover... Men han har ihvertfald lavet noget om der måske er relevant for dig :P )

2020-12-03 07:53 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication.Android/Wifi.cs
>          public void ConnectToWifi(string ssid)
aaah, ok det vidste jeg ikke! modtaget

2020-12-03 07:53 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/Helpers/NorthCommands.cs
> +    {
Det fordi den virksomhed som producerer rover og base hedder North :D

2020-12-07 12:03 UTC, MartinBruun requested changes
Super fedt! Der er lige nogle små kommentarer :)

Hvis der er noget du er i tvivl om, så tager du bare fat i mig!

2020-12-07 12:03 UTC, MartinBruun commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +            string URL = "http://192.168.80.1:8888/rover";
+ lav evt. en string hvor din "http://192..." streng bliver beskrevet.
Regner med det er RoverAccessPoint eller lign. Men er lidt usikker :)

2020-12-07 12:03 UTC, MartinBruun commented on TurfTankRegistrationApplication/TestUnit/ViewModel/RoverRegVMTest.cs
> +        {
Hvis du implementere App.WifiClient istedet for at lave en ny HttpClient, så kan du mocke dit response, så du kan beskrive præcis hvad du ønsker at få fra din PostAsync :)

Tror det er det der går galt i din test her, nu hvor din "fakede" json response ikke er sat længere.

2020-12-07 19:07 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TestUnit/ViewModel/RoverRegVMTest.cs
> +            string actual = testObject.RoverResponse;
Jamen det er den skide test her. Jeg ved simpelthen ikke hvorfor det ikke virker. Jeg forsøgte at smide den der delay ind for at se om det var fordi den ikke kunne finde ud af at håndtere async i test.... men det hjælper stadig ikke

2020-12-07 19:07 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TestUnit/ViewModel/RoverRegVMTest.cs
> +            string actual = testObject.RoverResponse;
+ at koden er helt anderledes nu så testen skal opdateres

2020-12-07 19:08 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +            string URL = "http://192.168.80.1:8888/rover";
Lad os lige kigge på det sammen under refaktoreringen. Det lyder fornuftigt, jeg kan bare ikke lige wrappe mit hoved om det lige nu

2020-12-07 19:10 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +        private async Task<bool> StopInmark()
Jeps korrekt. Hvis man ønsker at ændre ting på robotten/roveren skal den sættes i configuration mode og dette gøres ved at kalde stopInmark og dernæst startInmark for derefter at kunne teste den igen, Hvis ikke der bliver kaldt startInmark vil Flemming ikke kunne teste den.

2020-12-07 19:10 UTC, Rallefar1103 commented on TurfTankRegistrationApplication/TurfTankRegistrationApplication/ViewModel/RoverRegistrationViewModel.cs
> +//var response = await http.GetAsync("https://jsonplaceholder.typicode.com/users");
Ja, men grunden til at jeg beholder det er for at vi har noget at kunne fake til eksamen.

2020-12-08 10:27 UTC, MartinBruun approved these changes

2020-12-08 10:33 UTC, merged